modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://example.org/issues"

[[mods]]
modId = "example_mod"
version = "${file.jarVersion}"
displayName = "__MOD_NAME__"
displayURL = "https://example.org/examplemod"
logoFile = "logo.png"
credits = ""
authors = "__MOD_AUTHOR__"
description = '''__MOD_DESCRIPTION__'''

[[dependencies.example_mod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
