modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://example.org/issues"

[[mods]]
modId = "example_mod"
version = "${file.jarVersion}"
displayName = "__MOD_NAME__"
displayURL = "https://example.org/examplemod"
logoFile = "logo.png"
credits = ""
authors = "__MOD_AUTHOR__"
description = '''__MOD_DESCRIPTION__'''

[[dependencies.example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
